bsd_mouse: include sys/stat.h directly instead of relying on xf86_OSlib.h
xf86_OSlib.h used to include sys/stat.h but that was recently removed by
xorg/xserver@5057c716eb5960f6971be620ce03a808d0f191ac so we need to do
it here now.

Fixes compiler errors:
bsd_mouse.c: In function 'FindDevice':
bsd_mouse.c:282:17: error: storage size of 'devMouseStat' isn't known
  282 |     struct stat devMouseStat;
      |                 ^~~~~~~~~~~~
bsd_mouse.c:283:17: error: storage size of 'sb' isn't known
  283 |     struct stat sb;
      |                 ^~
bsd_mouse.c:298:21: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]
  298 |                 if (fstat(fd, &devMouseStat) == 0)
      |                     ^~~~~
bsd_mouse.c:298:21: warning: nested extern declaration of 'fstat' [-Wnested-externs]
bsd_mouse.c:283:17: warning: unused variable 'sb' [-Wunused-variable]
  283 |     struct stat sb;
      |                 ^~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-input-mouse/-/merge_requests/12>